[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc-endpoints = { sepolia-eth="https://eth-mainnet.g.alchemy.com/v2/_TWA_qo5DWneRstbX5PaobSBZW10-NVo", arb-sepolia="https://arb-mainnet.g.alchemy.com/v2/bna0YW5wJhWwnD3Ugaj8lcFUAlaMSK1W"}

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
              "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
              "@ccip/contracts=lib/ccip/contracts"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
