[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc-endpoints = { eth="https://eth-sepolia.g.alchemy.com/v2/_TWA_qo5DWneRstbX5PaobSBZW10-NVo", arb="https://arb-sepolia.g.alchemy.com/v2/bna0YW5wJhWwnD3Ugaj8lcFUAlaMSK1W"}
#viaIR = true
optimizer = true
optimizer_runs = 200

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
              "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
              "@ccip/contracts=lib/ccip/contracts",
              "@chainlink-local=lib/chainlink-local",
              "forge-std=lib/forge-std/src"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
